In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../0331新数据/热力数据/TC-data-100w.csv',low_memory=False)

In [3]:
data = data[data['lon2'] > 31].reset_index(drop=True)

In [4]:
MIN_LON = 103.90
MAX_LON = 104.21
MIN_LAT = 30.53
MAX_LAT = 30.82

# 微观

In [5]:
N_BINS_LON = 9  # M
N_BINS_LAT = 12  # N

In [6]:
H, lon_edges, lat_edges = np.histogram2d(
    x=data['lat2'],    # Y 轴数据 (纬度)
    y=data['lon2'],    # X 轴数据 (经度)
    bins=[N_BINS_LAT, N_BINS_LON], # [N, M] 网格分辨率
    range=[[MIN_LAT, MAX_LAT], [MIN_LON, MAX_LON]] # [Y轴边界, X轴边界]
)

In [7]:
print(f"生成的矩阵 H 的形状: {H.shape}")
print("(N, M) = (纬度格子数, 经度格子数)")
print("\n生成的矩阵 H (部分示例):")
print(H)

生成的矩阵 H 的形状: (12, 9)
(N, M) = (纬度格子数, 经度格子数)

生成的矩阵 H (部分示例):
[[0.0000e+00 0.0000e+00 0.0000e+00 1.7810e+03 1.2205e+04 3.7100e+02
  8.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.3510e+03 1.8910e+03 1.3229e+04 9.3700e+02
  2.0700e+02 7.3000e+01 0.0000e+00]
 [0.0000e+00 0.0000e+00 8.3700e+02 4.6560e+03 1.9772e+04 1.9534e+04
  1.7354e+04 1.0507e+04 0.0000e+00]
 [0.0000e+00 1.5900e+02 1.9780e+03 5.3570e+03 2.5516e+04 4.5641e+04
  3.1095e+04 1.0137e+04 0.0000e+00]
 [0.0000e+00 3.7000e+01 1.3532e+04 2.4591e+04 3.2416e+04 5.3873e+04
  4.8341e+04 8.4340e+03 0.0000e+00]
 [9.1700e+02 1.0477e+04 1.9932e+04 3.1170e+04 6.8907e+04 7.5061e+04
  3.6894e+04 2.3210e+03 0.0000e+00]
 [1.5740e+03 7.3270e+03 1.9719e+04 4.3384e+04 3.5615e+04 4.8422e+04
  1.8671e+04 6.7660e+03 2.1750e+03]
 [2.0000e+01 8.0700e+02 1.2752e+04 1.9694e+04 2.8369e+04 3.6803e+04
  9.7750e+03 1.5382e+04 1.8640e+03]
 [0.0000e+00 0.0000e+00 6.8900e+02 7.5660e+03 5.3680e+03 9.5200e+02
  3.3750e+03 1.8000e+02 0.0000e+00]
 [

In [8]:
H.shape

(12, 9)

In [9]:
min(data['lat2'])

30.53281725

In [10]:
max(data['lat2'])

30.81665103

In [11]:
min(data['lon2'])

103.9078419

In [12]:
max(data['lon2'])

104.2168058

In [13]:
pd.DataFrame(H)

0        1        2        3        4        5        6        7   
0      0.0      0.0      0.0   1781.0  12205.0    371.0      8.0      0.0  \
1      0.0      0.0   1351.0   1891.0  13229.0    937.0    207.0     73.0   
2      0.0      0.0    837.0   4656.0  19772.0  19534.0  17354.0  10507.0   
3      0.0    159.0   1978.0   5357.0  25516.0  45641.0  31095.0  10137.0   
4      0.0     37.0  13532.0  24591.0  32416.0  53873.0  48341.0   8434.0   
5    917.0  10477.0  19932.0  31170.0  68907.0  75061.0  36894.0   2321.0   
6   1574.0   7327.0  19719.0  43384.0  35615.0  48422.0  18671.0   6766.0   
7     20.0    807.0  12752.0  19694.0  28369.0  36803.0   9775.0  15382.0   
8      0.0      0.0    689.0   7566.0   5368.0    952.0   3375.0    180.0   
9      0.0      0.0    202.0      0.0    690.0   2291.0   3651.0      0.0   
10     0.0      0.0      0.0      0.0      9.0   1075.0    219.0      0.0   
11     0.0      0.0      0.0      0.0      0.0     41.0      0.0      0.0   

         8  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
5      0.0  
6   2175.0  
7   1864.0  
8      0.0  
9      0.0  
10     0.0  
11   164.0

# 宏观

In [15]:
N_BINS_LON = 6  # M
N_BINS_LAT = 4  # N

In [16]:
H, lon_edges, lat_edges = np.histogram2d(
    x=data['lat2'],    # Y 轴数据 (纬度)
    y=data['lon2'],    # X 轴数据 (经度)
    bins=[N_BINS_LAT, N_BINS_LON], # [N, M] 网格分辨率
    range=[[MIN_LAT, MAX_LAT], [MIN_LON, MAX_LON]] # [Y轴边界, X轴边界]
)

In [17]:
print(f"生成的矩阵 H 的形状: {H.shape}")
print("(N, M) = (纬度格子数, 经度格子数)")
print("\n生成的矩阵 H (部分示例):")
print(H)

生成的矩阵 H 的形状: (4, 6)
(N, M) = (纬度格子数, 经度格子数)

生成的矩阵 H (部分示例):
[[0.00000e+00 2.18800e+03 2.05090e+04 5.38670e+04 2.76760e+04 4.73000e+02]
 [1.18500e+03 4.58470e+04 1.10521e+05 2.52011e+05 1.37123e+05 9.90000e+01]
 [2.03700e+03 4.08510e+04 1.17194e+05 1.08979e+05 3.28480e+04 2.53400e+04]
 [0.00000e+00 2.02000e+02 6.90000e+02 3.41600e+03 3.87000e+03 1.64000e+02]]


In [18]:
pd.DataFrame(H)

0        1         2         3         4        5
0     0.0   2188.0   20509.0   53867.0   27676.0    473.0
1  1185.0  45847.0  110521.0  252011.0  137123.0     99.0
2  2037.0  40851.0  117194.0  108979.0   32848.0  25340.0
3     0.0    202.0     690.0    3416.0    3870.0    164.0